In [1]:
import torch
from torch import nn
import torch.nn.functional as F

/home/wislab/anaconda3/envs/gram-hd/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
input = torch.arange(1, 5, dtype=torch.float32).view(1, 1, 2, 2)
input

tensor([[[[1., 2.],
          [3., 4.]]]])

In [3]:
x = F.interpolate(input, scale_factor=2, mode='nearest')
x

tensor([[[[1., 1., 2., 2.],
          [1., 1., 2., 2.],
          [3., 3., 4., 4.],
          [3., 3., 4., 4.]]]])

In [4]:
x = F.interpolate(input, scale_factor=2, mode='bilinear', align_corners=False)
x

tensor([[[[1.0000, 1.2500, 1.7500, 2.0000],
          [1.5000, 1.7500, 2.2500, 2.5000],
          [2.5000, 2.7500, 3.2500, 3.5000],
          [3.0000, 3.2500, 3.7500, 4.0000]]]])

In [5]:
F.grid_sample

<function torch.nn.functional.grid_sample(input: torch.Tensor, grid: torch.Tensor, mode: str = 'bilinear', padding_mode: str = 'zeros', align_corners: Union[bool, NoneType] = None) -> torch.Tensor>

In [6]:
ray_start = 23
ray_end = 8
num_samples = 48
x = torch.linspace(ray_start, ray_end, num_samples)
x, x.shape

(tensor([23.0000, 22.6809, 22.3617, 22.0426, 21.7234, 21.4043, 21.0851, 20.7660,
         20.4468, 20.1277, 19.8085, 19.4894, 19.1702, 18.8511, 18.5319, 18.2128,
         17.8936, 17.5745, 17.2553, 16.9362, 16.6170, 16.2979, 15.9787, 15.6596,
         15.3404, 15.0213, 14.7021, 14.3830, 14.0638, 13.7447, 13.4255, 13.1064,
         12.7872, 12.4681, 12.1489, 11.8298, 11.5106, 11.1915, 10.8723, 10.5532,
         10.2340,  9.9149,  9.5957,  9.2766,  8.9574,  8.6383,  8.3191,  8.0000]),
 torch.Size([48]))

In [9]:
y = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
y, y.shape

(tensor([[[1, 2],
          [3, 4]],
 
         [[5, 6],
          [7, 8]]]),
 torch.Size([2, 2, 2]))

In [12]:
y = y.unsqueeze(-2)
y, y.shape

(tensor([[[[[1, 2]]],
 
 
          [[[3, 4]]]],
 
 
 
         [[[[5, 6]]],
 
 
          [[[7, 8]]]]]),
 torch.Size([2, 2, 1, 1, 2]))

In [13]:
import numpy as np

file_path = './datasets/carla/poses/000000_pose.npy'

In [16]:
data = np.load(file_path)
data

array([[ 9.5078254e-01,  1.5812661e-01, -2.6647440e-01, -2.6647508e+00],
       [-3.0982208e-01,  4.9843812e-01, -8.0967259e-01, -8.0967226e+00],
       [ 4.7902255e-03,  8.5238224e-01,  5.2289736e-01,  5.2289743e+00]],
      dtype=float32)

In [17]:
data.shape

(3, 4)

In [24]:
def read_pose_npy(name,flip=False):
    P = np.load(name)
    P_x = P[0] + 0.14
    if not flip:
        P_y = P[1]
    else:
        P_y = -P[1]

    P_ = np.array([P_x,P_y])
    P = torch.tensor([P_x,P_y],dtype=torch.float32)

    return P

In [25]:
P = read_pose_npy(file_path)
P

/tmp/ipykernel_1542373/2437399524.py:10: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  /opt/conda/conda-bld/pytorch_1646755903507/work/torch/csrc/utils/tensor_new.cpp:210.)
  P = torch.tensor([P_x,P_y],dtype=torch.float32)


tensor([[ 1.0908,  0.2981, -0.1265, -2.5248],
        [-0.3098,  0.4984, -0.8097, -8.0967]])

In [26]:
P.shape

torch.Size([2, 4])